{% set name = "typhoeus" %}
{% set version = "1.5.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 120b67ed1ef515e6c0e938176db880f15b0916f038e78ce2a66290f3f1de3e3b

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-ethon >=0.9.0,<0.10

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Typhoeus runs HTTP requests in parallel while cleanly encapsulating handling logic.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/typhoeus/{{ name }}

extra:
  recipe-maintainers:
    - sodre
