travis:
  secure:
    BINSTAR_TOKEN: lKgay9m9J+tbODtL87qlvoLTeB3bc+D11bFN+bMmxk6yf1L8wVdiPgCW1JFg0bEYqOUJnp+QlMM7BKSd4TGf3iJ/bV3jvuZzFQs79pdeMh3V89wUYKAZUUcr4Y3jxZILNVCWHvNbRbengBtdgcSEM4z4zs4oxxqH4T2n68uflgnOtVAiFQfpP61kt0CqeWSlIgVhIrtINyQc+Knf+8A5xGQioCseGRL9qGs+5qSak70XraeVkIoWI11lx8N6HYXAFiMhnD4W3GjUxd4jMgchrBIDnhvdr/zTZ1oc1LAzX0ke6miWBrFK73k6NuTpl2YDa6EAWXf9s2BTAos8GLfICvTKjJa4b5ak7ZUHXyURmnoH22XBW+SyF+LOWgieFHFHIe8Sc1oWmQPtw8IFk6ZsedFqsguNG9ho7vRNAgL0XBuAl9EHlMXac0IezO/MCvfodBc7v/st8wfsc2PsezivnYeXHxMGMOIEwLNRixBWRy2RqFGRsXI+j5YC2CW0lYVZnZby0MCe8IoWqMkzFgqszUVWJWHyZwEZUdAsV9YsGYTNs9+f6WWOYGNdyXX6+r6/lfvEj4+hvVH8L1G9y4UphsVGwVi5XLkJn+A2gbok6yOHJyt8ShyoDo3h2mxa0Tl3Q1vglLJezV1aRFUL8YQU7g6hfpapvXX49UQCChHbqyw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
